-- begin REGOFCARDSMAGIC_PEOPLE
create unique index IDX_REGOFCARDSMAGIC_PEOPLE_UNIQ_DCI on REGOFCARDSMAGIC_PEOPLE (DCI) ^
-- end REGOFCARDSMAGIC_PEOPLE
-- begin REGOFCARDSMAGIC_DECK
alter table REGOFCARDSMAGIC_DECK add constraint FK_REGOFCARDSMAGIC_DECK_ON_OWNER foreign key (OWNER_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
create index IDX_REGOFCARDSMAGIC_DECK_ON_OWNER on REGOFCARDSMAGIC_DECK (OWNER_ID)^
-- end REGOFCARDSMAGIC_DECK
-- begin REGOFCARDSMAGIC_CARD
alter table REGOFCARDSMAGIC_CARD add constraint FK_REGOFCARDSMAGIC_CARD_ON_OWNER foreign key (OWNER_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
alter table REGOFCARDSMAGIC_CARD add constraint FK_REGOFCARDSMAGIC_CARD_ON_DECK foreign key (DECK_ID) references REGOFCARDSMAGIC_DECK(ID)^
create index IDX_REGOFCARDSMAGIC_CARD_ON_OWNER on REGOFCARDSMAGIC_CARD (OWNER_ID)^
create index IDX_REGOFCARDSMAGIC_CARD_ON_DECK on REGOFCARDSMAGIC_CARD (DECK_ID)^
-- end REGOFCARDSMAGIC_CARD
-- begin REGOFCARDSMAGIC_CONTRIBUTION
alter table REGOFCARDSMAGIC_CONTRIBUTION add constraint FK_REGOFCARDSMAGIC_CONTRIBUTION_ON_PEOPLE foreign key (PEOPLE_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
alter table REGOFCARDSMAGIC_CONTRIBUTION add constraint FK_REGOFCARDSMAGIC_CONTRIBUTION_ON_TYPE foreign key (TYPE_ID) references REGOFCARDSMAGIC_TYPES(ID)^
create index IDX_REGOFCARDSMAGIC_CONTRIBUTION_ON_PEOPLE on REGOFCARDSMAGIC_CONTRIBUTION (PEOPLE_ID)^
create index IDX_REGOFCARDSMAGIC_CONTRIBUTION_ON_TYPE on REGOFCARDSMAGIC_CONTRIBUTION (TYPE_ID)^
-- end REGOFCARDSMAGIC_CONTRIBUTION
-- begin REGOFCARDSMAGIC_TYPES
alter table REGOFCARDSMAGIC_TYPES add constraint FK_REGOFCARDSMAGIC_TYPES_ON_TYPE foreign key (TYPE_ID) references REGOFCARDSMAGIC_TYPES(ID)^
create index IDX_REGOFCARDSMAGIC_TYPES_ON_TYPE on REGOFCARDSMAGIC_TYPES (TYPE_ID)^
-- end REGOFCARDSMAGIC_TYPES
-- begin REGOFCARDSMAGIC_TOURNAMENT
alter table REGOFCARDSMAGIC_TOURNAMENT add constraint FK_REGOFCARDSMAGIC_TOURNAMENT_ON_TYPE foreign key (TYPE_ID) references REGOFCARDSMAGIC_TYPES(ID)^
alter table REGOFCARDSMAGIC_TOURNAMENT add constraint FK_REGOFCARDSMAGIC_TOURNAMENT_ON_PEOPLE foreign key (PEOPLE_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
create index IDX_REGOFCARDSMAGIC_TOURNAMENT_ON_TYPE on REGOFCARDSMAGIC_TOURNAMENT (TYPE_ID)^
create index IDX_REGOFCARDSMAGIC_TOURNAMENT_ON_PEOPLE on REGOFCARDSMAGIC_TOURNAMENT (PEOPLE_ID)^
-- end REGOFCARDSMAGIC_TOURNAMENT
