-- begin REGOFCARDSMAGIC_PEOPLE
alter table REGOFCARDSMAGIC_PEOPLE add constraint FK_REGOFCARDSMAGIC_PEOPLE_ON_POSITION_IN_TEAM foreign key (POSITION_IN_TEAM_ID) references REGOFCARDSMAGIC_POSITION_IN_TEAM(ID)^
create unique index IDX_REGOFCARDSMAGIC_PEOPLE_UK_DCI on REGOFCARDSMAGIC_PEOPLE (DCI) where DELETE_TS is null ^
create index IDX_REGOFCARDSMAGIC_PEOPLE_ON_POSITION_IN_TEAM on REGOFCARDSMAGIC_PEOPLE (POSITION_IN_TEAM_ID)^
-- end REGOFCARDSMAGIC_PEOPLE
-- begin REGOFCARDSMAGIC_DECK
alter table REGOFCARDSMAGIC_DECK add constraint FK_REGOFCARDSMAGIC_DECK_ON_OWNER foreign key (OWNER_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
create index IDX_REGOFCARDSMAGIC_DECK_ON_OWNER on REGOFCARDSMAGIC_DECK (OWNER_ID)^
-- end REGOFCARDSMAGIC_DECK
-- begin REGOFCARDSMAGIC_CARD
alter table REGOFCARDSMAGIC_CARD add constraint FK_REGOFCARDSMAGIC_CARD_ON_OWNER foreign key (OWNER_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
alter table REGOFCARDSMAGIC_CARD add constraint FK_REGOFCARDSMAGIC_CARD_ON_DECK foreign key (DECK_ID) references REGOFCARDSMAGIC_DECK(ID)^
create index IDX_REGOFCARDSMAGIC_CARD_ON_OWNER on REGOFCARDSMAGIC_CARD (OWNER_ID)^
create index IDX_REGOFCARDSMAGIC_CARD_ON_DECK on REGOFCARDSMAGIC_CARD (DECK_ID)^
-- end REGOFCARDSMAGIC_CARD
-- begin REGOFCARDSMAGIC_CONTRIBUTION
alter table REGOFCARDSMAGIC_CONTRIBUTION add constraint FK_REGOFCARDSMAGIC_CONTRIBUTION_ON_PEOPLE foreign key (PEOPLE_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
alter table REGOFCARDSMAGIC_CONTRIBUTION add constraint FK_REGOFCARDSMAGIC_CONTRIBUTION_ON_TYPE foreign key (TYPE_ID) references REGOFCARDSMAGIC_TYPES(ID)^
create index IDX_REGOFCARDSMAGIC_CONTRIBUTION_ON_PEOPLE on REGOFCARDSMAGIC_CONTRIBUTION (PEOPLE_ID)^
create index IDX_REGOFCARDSMAGIC_CONTRIBUTION_ON_TYPE on REGOFCARDSMAGIC_CONTRIBUTION (TYPE_ID)^
-- end REGOFCARDSMAGIC_CONTRIBUTION
-- begin REGOFCARDSMAGIC_TYPES
alter table REGOFCARDSMAGIC_TYPES add constraint FK_REGOFCARDSMAGIC_TYPES_ON_TYPE foreign key (TYPE_ID) references REGOFCARDSMAGIC_TYPES(ID)^
create index IDX_REGOFCARDSMAGIC_TYPES_ON_TYPE on REGOFCARDSMAGIC_TYPES (TYPE_ID)^
-- end REGOFCARDSMAGIC_TYPES
-- begin REGOFCARDSMAGIC_TOURNAMENT
alter table REGOFCARDSMAGIC_TOURNAMENT add constraint FK_REGOFCARDSMAGIC_TOURNAMENT_ON_TYPE foreign key (TYPE_ID) references REGOFCARDSMAGIC_TYPES(ID)^
alter table REGOFCARDSMAGIC_TOURNAMENT add constraint FK_REGOFCARDSMAGIC_TOURNAMENT_ON_PEOPLE foreign key (PEOPLE_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
create index IDX_REGOFCARDSMAGIC_TOURNAMENT_ON_TYPE on REGOFCARDSMAGIC_TOURNAMENT (TYPE_ID)^
create index IDX_REGOFCARDSMAGIC_TOURNAMENT_ON_PEOPLE on REGOFCARDSMAGIC_TOURNAMENT (PEOPLE_ID)^
-- end REGOFCARDSMAGIC_TOURNAMENT
-- begin REGOFCARDSMAGIC_TEAM
alter table REGOFCARDSMAGIC_TEAM add constraint FK_REGOFCARDSMAGIC_TEAM_ON_TEAM_MATES foreign key (TEAM_MATES_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
create index IDX_REGOFCARDSMAGIC_TEAM_ON_TEAM_MATES on REGOFCARDSMAGIC_TEAM (TEAM_MATES_ID)^
-- end REGOFCARDSMAGIC_TEAM
-- begin REGOFCARDSMAGIC_STORAGE
alter table REGOFCARDSMAGIC_STORAGE add constraint FK_REGOFCARDSMAGIC_STORAGE_ON_CARD foreign key (CARD_ID) references REGOFCARDSMAGIC_CARD(ID)^
create index IDX_REGOFCARDSMAGIC_STORAGE_ON_CARD on REGOFCARDSMAGIC_STORAGE (CARD_ID)^
-- end REGOFCARDSMAGIC_STORAGE
-- begin REGOFCARDSMAGIC_COLLECTION_OF_CARDS
alter table REGOFCARDSMAGIC_COLLECTION_OF_CARDS add constraint FK_REGOFCARDSMAGIC_COLLECTION_OF_CARDS_ON_CARD foreign key (CARD_ID) references REGOFCARDSMAGIC_CARD(ID)^
create index IDX_REGOFCARDSMAGIC_COLLECTION_OF_CARDS_ON_CARD on REGOFCARDSMAGIC_COLLECTION_OF_CARDS (CARD_ID)^
-- end REGOFCARDSMAGIC_COLLECTION_OF_CARDS
-- begin REGOFCARDSMAGIC_RENT_CARDS
alter table REGOFCARDSMAGIC_RENT_CARDS add constraint FK_REGOFCARDSMAGIC_RENT_CARDS_ON_CARD foreign key (CARD_ID) references REGOFCARDSMAGIC_CARD(ID)^
alter table REGOFCARDSMAGIC_RENT_CARDS add constraint FK_REGOFCARDSMAGIC_RENT_CARDS_ON_TO_WHO foreign key (TO_WHO_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
create index IDX_REGOFCARDSMAGIC_RENT_CARDS_ON_CARD on REGOFCARDSMAGIC_RENT_CARDS (CARD_ID)^
create index IDX_REGOFCARDSMAGIC_RENT_CARDS_ON_TO_WHO on REGOFCARDSMAGIC_RENT_CARDS (TO_WHO_ID)^
-- end REGOFCARDSMAGIC_RENT_CARDS
-- begin REGOFCARDSMAGIC_CARD_FOR_TRADE
alter table REGOFCARDSMAGIC_CARD_FOR_TRADE add constraint FK_REGOFCARDSMAGIC_CARD_FOR_TRADE_ON_CARD foreign key (CARD_ID) references REGOFCARDSMAGIC_CARD(ID)^
create index IDX_REGOFCARDSMAGIC_CARD_FOR_TRADE_ON_CARD on REGOFCARDSMAGIC_CARD_FOR_TRADE (CARD_ID)^
-- end REGOFCARDSMAGIC_CARD_FOR_TRADE
-- begin REGOFCARDSMAGIC_CARD_EXCHANGE
alter table REGOFCARDSMAGIC_CARD_EXCHANGE add constraint FK_REGOFCARDSMAGIC_CARD_EXCHANGE_ON_BUYER foreign key (BUYER_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
alter table REGOFCARDSMAGIC_CARD_EXCHANGE add constraint FK_REGOFCARDSMAGIC_CARD_EXCHANGE_ON_SELLER foreign key (SELLER_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
alter table REGOFCARDSMAGIC_CARD_EXCHANGE add constraint FK_REGOFCARDSMAGIC_CARD_EXCHANGE_ON_CARDS_FOR_BUY foreign key (CARDS_FOR_BUY_ID) references REGOFCARDSMAGIC_CARD(ID)^
alter table REGOFCARDSMAGIC_CARD_EXCHANGE add constraint FK_REGOFCARDSMAGIC_CARD_EXCHANGE_ON_CARDS_FOR_SALE foreign key (CARDS_FOR_SALE_ID) references REGOFCARDSMAGIC_CARD(ID)^
create index IDX_REGOFCARDSMAGIC_CARD_EXCHANGE_ON_BUYER on REGOFCARDSMAGIC_CARD_EXCHANGE (BUYER_ID)^
create index IDX_REGOFCARDSMAGIC_CARD_EXCHANGE_ON_SELLER on REGOFCARDSMAGIC_CARD_EXCHANGE (SELLER_ID)^
create index IDX_REGOFCARDSMAGIC_CARD_EXCHANGE_ON_CARDS_FOR_BUY on REGOFCARDSMAGIC_CARD_EXCHANGE (CARDS_FOR_BUY_ID)^
create index IDX_REGOFCARDSMAGIC_CARD_EXCHANGE_ON_CARDS_FOR_SALE on REGOFCARDSMAGIC_CARD_EXCHANGE (CARDS_FOR_SALE_ID)^
-- end REGOFCARDSMAGIC_CARD_EXCHANGE
-- begin REGOFCARDSMAGIC_COMPENSATION
alter table REGOFCARDSMAGIC_COMPENSATION add constraint FK_REGOFCARDSMAGIC_COMPENSATION_ON_PEOPLE foreign key (PEOPLE_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
alter table REGOFCARDSMAGIC_COMPENSATION add constraint FK_REGOFCARDSMAGIC_COMPENSATION_ON_POSITION_IN_TEAM foreign key (POSITION_IN_TEAM_ID) references REGOFCARDSMAGIC_POSITION_IN_TEAM(ID)^
create index IDX_REGOFCARDSMAGIC_COMPENSATION_ON_PEOPLE on REGOFCARDSMAGIC_COMPENSATION (PEOPLE_ID)^
create index IDX_REGOFCARDSMAGIC_COMPENSATION_ON_POSITION_IN_TEAM on REGOFCARDSMAGIC_COMPENSATION (POSITION_IN_TEAM_ID)^
-- end REGOFCARDSMAGIC_COMPENSATION
-- begin REGOFCARDSMAGIC_TRADE
alter table REGOFCARDSMAGIC_TRADE add constraint FK_REGOFCARDSMAGIC_TRADE_ON_SELLER foreign key (SELLER_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
alter table REGOFCARDSMAGIC_TRADE add constraint FK_REGOFCARDSMAGIC_TRADE_ON_BUYER foreign key (BUYER_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
alter table REGOFCARDSMAGIC_TRADE add constraint FK_REGOFCARDSMAGIC_TRADE_ON_CARD foreign key (CARD_ID) references REGOFCARDSMAGIC_CARD(ID)^
create index IDX_REGOFCARDSMAGIC_TRADE_ON_SELLER on REGOFCARDSMAGIC_TRADE (SELLER_ID)^
create index IDX_REGOFCARDSMAGIC_TRADE_ON_BUYER on REGOFCARDSMAGIC_TRADE (BUYER_ID)^
create index IDX_REGOFCARDSMAGIC_TRADE_ON_CARD on REGOFCARDSMAGIC_TRADE (CARD_ID)^
-- end REGOFCARDSMAGIC_TRADE
-- begin REGOFCARDSMAGIC_RENT
alter table REGOFCARDSMAGIC_RENT add constraint FK_REGOFCARDSMAGIC_RENT_ON_SELLER foreign key (SELLER_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
alter table REGOFCARDSMAGIC_RENT add constraint FK_REGOFCARDSMAGIC_RENT_ON_BUYER foreign key (BUYER_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
alter table REGOFCARDSMAGIC_RENT add constraint FK_REGOFCARDSMAGIC_RENT_ON_CARD foreign key (CARD_ID) references REGOFCARDSMAGIC_CARD(ID)^
create index IDX_REGOFCARDSMAGIC_RENT_ON_SELLER on REGOFCARDSMAGIC_RENT (SELLER_ID)^
create index IDX_REGOFCARDSMAGIC_RENT_ON_BUYER on REGOFCARDSMAGIC_RENT (BUYER_ID)^
create index IDX_REGOFCARDSMAGIC_RENT_ON_CARD on REGOFCARDSMAGIC_RENT (CARD_ID)^
-- end REGOFCARDSMAGIC_RENT
-- begin REGOFCARDSMAGIC_PEOPLE_TEAM_LINK
alter table REGOFCARDSMAGIC_PEOPLE_TEAM_LINK add constraint FK_PEOTEA_ON_TEAM foreign key (TEAM_ID) references REGOFCARDSMAGIC_TEAM(ID)^
alter table REGOFCARDSMAGIC_PEOPLE_TEAM_LINK add constraint FK_PEOTEA_ON_PEOPLE foreign key (PEOPLE_ID) references REGOFCARDSMAGIC_PEOPLE(ID)^
-- end REGOFCARDSMAGIC_PEOPLE_TEAM_LINK
